= Введение в JavaScript

*JavaScript* — мультипарадигменный язык программирования. Поддерживает объектно-ориентированный, императивный и функциональный стили. *JavaScript* обычно используется как встраиваемый язык для программного доступа к объектам приложений. Наиболее широкое применение находит в браузерах как язык сценариев для придания интерактивности веб-страницам.

*JavaScript* является интерпретируемым языком, это означает, что код на языке *JavaScript* выполняется с помощью *интерпретатора*. Он получает инструкции языка *JavaScript*, которые определены на веб-странице, выполняет их (или интерпретирует).

== Основы синтаксиса javascript

Прежде чем переходить к детальному изучению основ языка программирования *javascript*, рассмотрим некоторые базовые моменты его синтаксиса.

Код *javascript* состоит из инструкций, каждая из которых завершается точкой запятой:

[source, javascript]
----
alert("Вычисление выражения"); var a = 5 + 8; alert(a);
----

Однако современные браузеры вполне могут различать отдельные инструкции, если они просто располагаются на отдельных строках без точки запятой:

[source, javascript]
----
alert("Вычисление выражения")
var a = 5 + 8
alert(a)
----

Но чтобы улучшить читабельность кода и снизить число возможных ошибок, рекомендуется определять каждую инструкцию *javascript* на отдельной строчке и завершать ее точкой с запятой, как в первом варианте.

В коде *javascript* могут использоваться *комментарии*, они не обрабатываются интерпретатором *javascript* и никак не учитываются в работе программы. Комментарии предназначен для ориентации по коду, чтобы указать, что делает тот или иной код.

*Комментарии* могут быть *однострочными*, для которых используется двойной слеш `//`:

[source, javascript]
----
// вывод сообщения
alert("Вычисление выражения");
// арифметическая операция
var a = 5 + 8;
alert(a);
----

Кроме однострочных комментариев могут использоваться и *многострочные*. Такие комментарии заключаются между символами `/* текст комментария */`. Например:

[source, javascript]
----
// вывод сообщения
/*  вывод сообщения и
 арифметическая операция */
alert("Вычисление выражения");
var a = 5 + 8;
alert(a);
----
