= Строки

== Строки и объект `String`

Для создания *строк* можно как напрямую присваивать переменной строку:

[source,js]
----
let name = "Tom";
----

Для работы со строками предназначен *объект `String`*, поэтому также можно использовать конструктор `String`:

[source,js]
----
var name = new String("Tom");
----

Но, как правило, используется первый более краткий способ. В первом случае JavaScript при необходимости автоматически преобразует переменную примитивного типа в объект `String`.

Объект `String` имеет большой набор свойств и методов, с помощью которых мы можем манипулировать строками.

Свойство `length` указывает на длину строки:

[source,js]
----
var hello = "привет мир";
console.log("В строке '" + hello + "' " + hello.length + " символов");
----

----
В строке 'привет мир' 10 символов
----

=== Шаблоны строк

*Шаблоны строк* позволяют вставлять в строку различные значения. Для этого строки заключаются в косые кавычки ```:

[source,js]
----
let name = "Tom";
let hello = `Hello ${name}`;
console.log(hello);

let age = 23;
let info = `${name} is ${age} years old`;
console.log(info);
----

----
Hello Tom
Tom is 23 years old
----

Для вставки значения в строку оно заключается в фигурные скобки, перед которыми ставится знак доллара `$`.

Также вместо *скалярных значений* могут добавляться *свойства сложных объектов* или *результаты выражений*.

=== Поиск в строке

Для поиска в строке некоторой подстроки используются методы `indexOf()` (индекс первого вхождения подстроки) и `lastIndexOf()` (индекс последнего вхождения подстроки*. Эти методы принимают два параметра:

* Подстроку, которую надо найти
* Необязательный параметр, который указывает, с какого символа следует проводить поиск подстроки в строке

Оба метода возвращают индекс символа, с которого в строке*начинается подстрока. Если подстрока не найдена, то возвращается число `-1`.

Еще один метод - `includes()` возвращает `true`, если строка содержит определенную подстроку. С помощью второго дополнительного параметра можно определить индекс, с которого будет начинаться поиск подстроки.

=== Выбор подстроки

Для того, что бы вырезать из строки подстроку, применяются методы `substr()` и `substring()`.

Метод `substring()` принимает два параметра:

* индекс символа в строке, начиная с которого надо проводить обрезку строки
* индекс, до которого надо обрезать строку

Метод `substr()` также в качестве первого параметра принимает начальный индекс подстроки, а в качестве второго - длину вырезаемой подстроки. Если второй параметр не указывается, то обрезается вся остальная часть строки.

=== Управление регистром

Для изменения регистра имеются методы `toLowerCase()` (для перевода в нижний регистр) и `toUpperCase()` (для перевода в верхний регистр).

=== Получение символа по индексу

Чтобы получить определенный символ в строке по индексу, можно применять методы `charAt()` и `charCodeAt()`. Оба метода в качестве параметра принимают индекс символа.

Но если в качестве результата метод `charAt()` возвращает сам символ, то метод `charCodeAt()` возвращает числовой код этого символа.

=== Удаление пробелов

Для удаления начальных и концевых пробелов в стоке используется метод `trim()`.

=== Объединение строк

Метод `concat()` объединяет две строки.

=== Замена подстроки

Метод `replace()` заменяет первое вхождение одной подстроки на другую.

=== Разделение строки

Метод `split()` разбивает строку на массив подстрок по определенному разделителю. В качестве разделителя используется строка, которая передается в метод.

=== Проверка начала и окончания строки

Метод `startsWith()` возвращает `true`, если строка начинается с определенной подстроки. А метод `endsWith()` возвращает `true`, если строка оканчивается на определенную подстроку. При этом играет роль регистр символов.

Дополнительный второй параметр позволяет указать индекс относительно которого будет проводиться сравнение.

== Объект `RegExp`

=== Регулярные выражения

*Регулярные выражения* представляют *шаблон*, который используется для поиска или модификации строки. Для работы с регулярными выражениями в JavaScript определен *объект `RegExp`*.

Определить регулярное выражение можно двумя способами:

[source,js]
----
var myExp = /hello/;
var myExp = new RegExp("hello");
----

=== Методы `RegExp`

Чтобы определить, соответствует ли регулярное выражение строке, в объекте `RegExp` определен метод `test()`. Этот метод возвращает `true`, если строка соответствует регулярному выражению, и `false`, если не соответствует.

[source,js]
----
var initialText = "hello world!";
var exp = /hello/;
var result = exp.test(initialText);
console.log(result);

initialText = "beautifull wheather";
result = exp.test(initialText);
console.log(result);
----

----
true
false
----

Аналогично работает метод `exec()` - он также проверяет, соответствует ли строка регулярному выражению, только теперь данный метод возвращает ту часть строки, которая соответствует выражению. Если соответствий нет, то возвращается значение `null`.

=== Группы символов

*Регулярное выражение* необязательно состоит из обычных строк, но также может включать *специальные элементы* синтаксиса регулярных выражений. Один из таких элементов представляют *группы символов*, заключенные в квадратные скобки.

[source,js]
----
var initialText = "обороноспособность";
var exp = /[абв]/;
----

Если нам надо определить наличие в строке буквенных символов из определенного диапазона, то можно разу задать этот диапазон:

[source,js]
----
var initialText = "обороноспособность";
var exp = /[а-я]/;
----

Если, наоборот, не надо, чтобы строка имела только определенные символы, то необходимо в квадратных скобках перед перечислением символов ставить знак `^`:

[source,js]
----
var initialText = "обороноспособность";
var exp = /[^а-я]/;
----

=== Свойства выражений

* Свойство `global` позволяет найти все подстроки, которые соответствуют регулярному выражению. По умолчанию при поиске подстрок регулярное выражение выбирает первую попавшуюся подстроку из строки, которая соответствует выражению. Хотя в строке может быть множество подстрок, которые также соответствуют выражению. Для этого применяется данное свойство в виде символа `g` в выражениях
* Свойство `ignoreCase` позволяет найти подстроки, которые соответствуют регулярному выражению, вне зависимости от регистра символов в строке. Для этого в регулярных выражениях применяется символ `i`
* Свойство `multiline` позволяет найти подстроки, которые соответствуют регулярному выражению, в многострочном тексте. Для этого в регулярных выражениях применяется символ `m`

[source,js]
----
var exp = /мир/i;
var exp = /мир/ig;
----

== Регулярные выражения в методах `String`

Ряд методов объекта `String` могут использовать регулярные выражения в качестве параметра.

=== Разделение строки. Метод `split()`

Метод `split()` может использовать регулярные выражения для разделения строк:

[source,js]
----
var initialText = "Сегодня была прекрасная погода";
var exp = /\s/;
var result = initialText.split(exp);
result.forEach(function(value, index, array) {
    console.log(value);
})
----

----
Сегодня
была
прекрасная
погода
----

=== Метод `match()`

Для поиска всех соответствий в строке применяется метод `match()`:

[source,js]
----
var initialText = "Он пришел домой и сделал домашнюю работу";
var exp = /дом[а-я]*/gi;
var result = initialText.match(exp);
result.forEach(function(value, index, array) {
    console.log(value);
})
----

----
домой
домашнюю
----

=== Поиск в строке. Метод `search()`

Метод `search()` находит индекс первого включения соответствия в строке:

[source,js]
----
var initialText = "hello world";
var exp = /wor/;
var result = initialText.search(exp);
console.log(result);
----

----
6
----

=== Замена. Метод `replace()`

Метод `replace()` позволяет заменить все соответствия регулярному выражению определенной строкой:

[source,js]
----
var menu = "Завтрак: каша, чай. Обед: суп, чай. Ужин: салат, чай.";
var exp = /чай/gi;
menu = menu.replace(exp, "кофе");
console.log(menu);
----

----
Завтрак: каша, кофе. Обед: суп, кофе. Ужин: салат, кофе.
----
