= Git для начинающих.Часть 3.Настройка Git
Статья посвещена вопросам настройки _Git_ в операционных системах _Windows_ и _Linux_. Рассмотрены вопросы настройки на системном, пользовательском уровне и уровне репозитория.

Настройка системы _Git_ предполагает, в первую очередь, указание имени пользователя и _e-mail_, которые используются для подписи коммитов и отправки изменений в удаленный репозиторий.

В _Git_ существует три места, где хранятся настройки:

*  на уровне системы;
*  на уровне пользователя;
*  на уровне проекта(репозитория).

Для того, чтобы сконфигурировать _Git_ на том или ином уровне вы можете изменить непосредственно конфигурационные файлы, но для этого нужно знать их формат, либо воспользоваться специальными командами, которые предоставляет _Git_. Мы рекомендуем использовать команды.

== Расположение конфигурационных файлов _Git_

=== _Windows_
Уровень системы

*\Program Files\Git\mingw64\etc\gitconfig*

Имейте ввиду, что для его изменения вам могут понадобиться права администратора!

Уровень пользователя

*%HOMEPATH%\.gitconfig*

Уровень репозитория

*папка_с_проектом\.git\config*

=== _Linux_

Уровень системы

*/etc/gitconfig*

Уровень пользователя

*~/.gitconfig*

Уровень репозитория

*папка_с_проектом/.git/config*

== Конфигурирование Git с помощью утилиты командной строки
Как уже было сказано выше, конфигурирование _Git_ с помощью утилиты командной строки – это наиболее удобный и безопасный способ. Независимо от того, на каком уровне вы хотите менять настройки, команда будет начинаться так:

====== _git config_

Для уровня системы, мы должны написать:

[source,shell script]
> git config --system

уровня пользователя:

[source,shell script]
> git config --global

уровня приложения:

[source,shell script]
> git config

После этой команды указывается параметр и его значение.

Например, зададим имя и _e-mail_ разработчика для уровня пользователя.

[source,shell script]
> git config --global user.name "User"

[source,shell script]
> git config --global user.email "user@company.com"

Для просмотра введенных изменений воспользуйтесь командой:

[source,shell script]
> git config --list

Дополнительно вы можете указать текстовый редактор, который будет запускать _Git_, если ему потребуется получить от вас какие-то данные, для этого модифицируйте параметр _core.editor_:

*** вариант для Linux:
[source,shell script]
> git config --global core.editor "nano"

*** вариант для Windows:
[source,shell script]
> git config --global core.editor "notepad.exe"