= Добавление, удаление и переименование файлов в репозитории

В рамках данного урока рассмотрим вопросы, касающиеся добавления, удаления и переименования файлов в git репозитории.

== Добавление файлов в _git_ репозиторий

Добавление файлов в репозиторий – это достаточно простая операция, мало чем отличающаяся от отправки изменений в отслеживаемых файлах в репозиторий. Мы уже не раз выполняли эту операцию в предыдущих уроках, но сделаем это ещё раз. Создадим новый репозиторий, для этого перейдите в каталог, в котором вы хотите его расположить и введите команду `git init`.

[source, shell script]
git init


Создайте в каталоге файл _README.md_ любым удобным для вас способом, мы сделаем это с помощью команды `touch`.

[source, shell script]
touch README.md

Теперь проверим состояние отслеживаемой директории.

[source, shell script]
----
git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        README.md

nothing added to commit but untracked files present (use "git add" to track)
----

Как вы можете видеть: в рабочей директории есть один неотслеживаемый файл _README.md_. Git нам подсказывает, что нужно сделать для того, чтобы начать отслеживать изменения в файле _README.md_: необходимо выполнить команду `git add`, сделаем это.

[source, shell script]
git add README.md

Посмотрим ещё раз на состояние.

[source, shell script]
----
git status
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   README.md
----

Видно, что информация о появлении нового файла попала в stage. Для того чтобы это изменение зафиксировалось в репозитории необходимо выполнить команду `git commit`.

[source, shell script]
----
git commit -m "add README.md file"
----

[source, shell script]
----
[master (root-commit) 0bb6c94] add README.md file
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README.md
----

Теперь в рабочей директории и в _stage_ нет объектов, информацию об изменении которых необходимо внести в репозиторий.

[source, shell script]
----
git status
On branch master
nothing to commit, working tree clean
----

В репозиторий был сделан один коммит.

[source, shell script]
----
git log --oneline
0bb6c94 add README.md file
----

== Удаление файлов из _git_ репозитория и из stage

=== Удаление файла из _stage_

Вначале разберемся со _stage_. Создадим ещё один файл.

[source, shell script]
touch main.c

“Отправим” файл _main.c_ в _stage_.

[source, shell script]
git add main.c

Внесем изменения в _README.md_.

[source, shell script]
echo "# README" > README.md

Информацию об этом также отправим в _stage_.

[source, shell script]
git add README.md

Посмотрим на состояние _stage_.

[source, shell script]
----
git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   README.md
        new file:   main.c
----

Если нам необходимо убрать из _stage_, какой-то из этих файлов (main.c или README.md), то для этого можно воспользоваться командой `git –rm cashell scripted <filename>`, сделаем это для файла _main.c_.

[source, shell script]
----
git rm --cached main.c
rm 'main.c'
----

Теперь посмотрим на состояние рабочей директории и _stage_.

[source, shell script]
----
git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   README.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        main.c
----

Видно, что изменения в файле _README.md_ готовы для коммита, а вот файл _main.c_ перешел в состояние – неотслеживаемый. Отправим _main.c_ в stage и, после этого, сделаем коммит в репозиторий.

[source,shell script]
----
git add main.c
git commit -m "add main.c and do some changes in README.md"
[master 49049bc] add main.c and do some changes in README.md
 2 files changed, 1 insertion(+)
 create mode 100644 main.c
----

== Удаление файлов из git репозитория

Удалить файл из репозитория можно двумя способами: *первый* – удалить его из рабочей директории и уведомить об этом _git_; *второй* – воспользоваться средствами _git_. *Начнем с первого способа.* Для начала посмотрим, какие файлы у нас хранятся в репозитории.

[source,shell script]
----
git ls-tree master
100644 blob 7e59600739c96546163833214c36459e324bad0a    README.md
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    main.c
----

Удалим файл _main.c_ из рабочей директории.

[source, shell script]
----
rm main.c
ls
README.md
----

Уведомим об этом систему _git_.

[source, shell script]
----
git rm main.c
rm 'main.c'
----

Вместо команды `git rm` можно использовать `git add`, но само слово `add` в данном случае будет звучать несколько неоднозначно, поэтому лучше использовать `rm`. На данном этапе еще можно вернуть все назад с помощью команды `git checkout` — `<filename>`, в результате, в нашу рабочую директорию будет скопирован файл из репозитория. Создадим коммит, фиксирующий удаление файла.

[source, shell script]
----
git commit -m "remove main.c"
[master d4e22ae] remove main.c
 1 file changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 main.c
----

Теперь в репозитории остался только один файл _README.md_.

[source, shell script]
----
git ls-tree master
100644 blob 7e59600739c96546163833214c36459e324bad0a    README.md
----

*Второй способ* – это сразу использовать команду `git rm` без предварительного удаления файла из директории. Вновь создадим файл _main.c_ и добавим его в репозиторий.

[source, shell script]
----
touch main.c
git add main.c
git commit -m "add main.c file"
[master 6d93049] add main.c file
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 main.c
git ls-tree master
100644 blob 7e59600739c96546163833214c36459e324bad0a    README.md
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    main.c
----

Удалим файл из репозитория.

[source, shell script]
----
git rm main.c
rm 'main.c'

git commit -m "deleted: main.c file"
[master ba7d027] deleted: main.c file
 1 file changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 main.c
----

Файла _main.c_ больше нет в репозитории.

[source, shell script]
----
git ls-tree master
100644 blob 7e59600739c96546163833214c36459e324bad0a    README.md
----

Его также нет и в рабочем каталоге.

[source,shell script]
----
ls
README.md
----

Удалите файл _README.md_ из репозитория самостоятельно.

== Переименование файлов в git репозитории

Как и в случае с удалением, переименовать файл в _git_ репозитории можно двумя способами – с использованием и без использования средств операционной системы.

*Первый способ*. Создадим файл _test_main_file.c_ и добавим его в репозиторий.

[source,shell script]
----
touch test_main_file.c

git add test_main_file.c

git commit -m "add test_main_file.c"
[master 6cf53ac] add test_main_file.c
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test_main_file.c
----

Содержимое репозитория после этого будет выглядеть так.

[source, shell script]
----
git ls-tree master
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    test_main_file.c
----

Переименуем его на _test_main.c_.

Сделаем это в рабочей директории.

[source, shell script]
mv test_main_file.c test_main.c

Теперь отправим изменение в репозиторий.

[source, shell script]
----
git add .
git commit -m "Rename test_main_file.c"
[master 79528c4] Rename test_main_file.c
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename test_main_file.c => test_main.c (100%)
----

В репозитории и в рабочей директории будет находится только файл _test_main.c_.

[source, shell script]
----
git ls-tree master
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    test_main.c

ls
test_main.c
----

*Второй способ.*

В рамках второго способа рассмотрим работу с командой `git mv`. Переименуем файл _test_main.c_ в _main.c_. Текущее содержимое репозитория и рабочего каталога.

[source, shell script]
----
git ls-tree master
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    test_main.c
ls
test_main.c
----

Переименуем файл _test_main.c_ на _main.c_ средствами _git_.

[source, shell script]
----
git mv test_main.c main.c

git commit -m "Rename test_main.c file"
[master c566f0e] Rename test_main.c file
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename test_main.c => main.c (100%)
----

Имя файла изменилось как в репозитории так и в рабочем каталоге.

[source, shell script]
----
git ls-tree master
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    main.c

ls
main.c
----