== *Git для начинающих. Часть 8. Добавление, удаление и переименование файлов в репозитории*

В рамках данного урока рассмотрим вопросы, касающиеся добавления, удаления и переименования файлов в git репозитории.

**** <<Добавление файлов в _git_ репозиторий>>
**** <<Удаление файлов из _git_ репозитория и из stage>>
- <<Удаление файла из _stage_>>
- <<Удаление файлов из git репозитория>>
*** xref:_удаление_файлов_из_git_репозитория[Первый способ].
*** xref:_удаление_файлов_из_git_репозитория[Второй способ].
**** <<Переименование файлов в git репозитории>>
- xref:_переименование_файлов_в_git_репозитории[Первый способ].
- xref:_переименование_файлов_в_git_репозитории[Второй способ].


=== Добавление файлов в _git_ репозиторий

Добавление файлов в репозиторий – это достаточно простая операция, мало чем отличающаяся от отправки изменений в отслеживаемых файлах в репозиторий. Мы уже не раз выполняли эту операцию в предыдущих уроках, но сделаем это ещё раз. Создадим новый репозиторий, для этого перейдите в каталог, в котором вы хотите его расположить и введите команду _git init_.

[source, sh]
> git init


Создайте в каталоге файл _README.md_ любым удобным для вас способом, мы сделаем это с помощью команды _touch_.

[source, sh]
> touch README.md

Теперь проверим состояние отслеживаемой директории.

[source, sh]
----
> git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        README.md

nothing added to commit but untracked files present (use "git add" to track)
----

Как вы можете видеть: в рабочей директории есть один неотслеживаемый файл _README.md. Git_ нам подсказывает, что нужно сделать для того, чтобы начать отслеживать изменения в файле _README.md_: необходимо выполнить команду _git add_, сделаем это.

[source, sh]
> git add README.md

Посмотрим ещё раз на состояние.

[source, sh]
----
> git status
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   README.md
----

Видно, что информация о появлении нового файла попала в stage. Для того чтобы это изменение зафиксировалось в репозитории необходимо выполнить команду _git commit_.

[source, sh]
----
> git commit -m "add README.md file"
[master (root-commit) 0bb6c94] add README.md file
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README.md
----

Теперь в рабочей директории и в _stage_ нет объектов, информацию об изменении которых необходимо внести в репозиторий.

[source, sh]
----
> git status
On branch master
nothing to commit, working tree clean
----

В репозиторий был сделан один коммит.

[source, sh]
----
> git log --oneline
0bb6c94 add README.md file
----

=== Удаление файлов из _git_ репозитория и из stage

==== Удаление файла из _stage_

Вначале разберемся со _stage_. Создадим ещё один файл.

[source, sh]
> touch main.c

“Отправим” файл _main.c_ в _stage_.

[source, sh]
> git add main.c

Внесем изменения в _README.md_.

[source, sh]
> echo "# README" > README.md

Информацию об этом также отправим в _stage_.

[source, sh]
> git add README.md

Посмотрим на состояние _stage_.

[source, sh]
----
> git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   README.md
        new file:   main.c
----

Если нам необходимо убрать из _stage_, какой-то из этих файлов (main.c или README.md), то для этого можно воспользоваться командой g__it –rm cashed <filename>__, сделаем это для файла _main.c_.

[source, sh]
----
> git rm --cached main.c
rm 'main.c'
----

Теперь посмотрим на состояние рабочей директории и _stage_.

[source, sh]
----
> git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   README.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        main.c
----

Видно, что изменения в файле _README.md_ готовы для коммита, а вот файл _main.c_ перешел в состояние – неотслеживаемый. Отправим _main.c_ в stage и, после этого, сделаем коммит в репозиторий.

[source,sh]
----
> git add main.c
> git commit -m "add main.c and do some changes in README.md"
[master 49049bc] add main.c and do some changes in README.md
 2 files changed, 1 insertion(+)
 create mode 100644 main.c
----

[#_удаление_файлов_из_git_репозитория]
=== Удаление файлов из git репозитория

Удалить файл из репозитория можно двумя способами: *первый* – удалить его из рабочей директории и уведомить об этом _git_; *второй* – воспользоваться средствами _git_. *Начнем с первого способа.* Для начала посмотрим, какие файлы у нас хранятся в репозитории.

[source,sh]
----
> git ls-tree master
100644 blob 7e59600739c96546163833214c36459e324bad0a    README.md
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    main.c
----

Удалим файл _main.c_ из рабочей директории.

[source, sh]
----
> rm main.c
> ls
README.md
----

Уведомим об этом систему _git_.

[source, sh]
----
> git rm main.c
rm 'main.c'
----

Вместо команды _git rm_ можно использовать _git add_, но само слово _add_ в данном случае будет звучать несколько неоднозначно, поэтому лучше использовать _rm_. На данном этапе еще можно вернуть все назад с помощью команды _git checkout_ — _<filename>_, в результате, в нашу рабочую директорию будет скопирован файл из репозитория. Создадим коммит, фиксирующий удаление файла.

[source, sh]
----
> git commit -m "remove main.c"
[master d4e22ae] remove main.c
 1 file changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 main.c
----

Теперь в репозитории остался только один файл _README.md_.

[source, sh]
----
> git ls-tree master
100644 blob 7e59600739c96546163833214c36459e324bad0a    README.md
----

*Второй способ* – это сразу использовать команду _git rm_ без предварительного удаления файла из директории. Вновь создадим файл _main.c_ и добавим его в репозиторий.

[source, sh]
----
> touch main.c
> git add main.c
> git commit -m "add main.c file"
[master 6d93049] add main.c file
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 main.c
> git ls-tree master
100644 blob 7e59600739c96546163833214c36459e324bad0a    README.md
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    main.c
----

Удалим файл из репозитория.

[source, sh]
----
> git rm main.c
rm 'main.c'

> git commit -m "deleted: main.c file"
[master ba7d027] deleted: main.c file
 1 file changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 main.c
----

Файла _main.c_ больше нет в репозитории.

[source, sh]
----
> git ls-tree master
100644 blob 7e59600739c96546163833214c36459e324bad0a    README.md
----

Его также нет и в рабочем каталоге.

[source,sh]
----
> ls
README.md
----

Удалите файл _README.md_ из репозитория самостоятельно.

[#_переименование_файлов_в_git_репозитории]
=== Переименование файлов в git репозитории

Как и в случае с удалением, переименовать файл в _git_ репозитории можно двумя способами – с использованием и без использования средств операционной системы.

*Первый способ*. Создадим файл _test_main_file.c_ и добавим его в репозиторий.

[source,sh]
----
> touch test_main_file.c

> git add test_main_file.c

> git commit -m "add test_main_file.c"
[master 6cf53ac] add test_main_file.c
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test_main_file.c
----

Содержимое репозитория после этого будет выглядеть так.

[source, sh]
----
> git ls-tree master
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    test_main_file.c
----

Переименуем его на _test_main.c_.

Сделаем это в рабочей директории.

[source, sh]
> mv test_main_file.c test_main.c

Теперь отправим изменение в репозиторий.

[source, sh]
----
> git add .
> git commit -m "Rename test_main_file.c"
[master 79528c4] Rename test_main_file.c
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename test_main_file.c => test_main.c (100%)
----

В репозитории и в рабочей директории будет находится только файл _test_main.c_.

[source, sh]
----
> git ls-tree master
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    test_main.c

> ls
test_main.c
----

*Второй способ.*

В рамках второго способа рассмотрим работу с командой _git mv_. Переименуем файл _test_main.c_ в _main.c_. Текущее содержимое репозитория и рабочего каталога.

[source, sh]
----
> git ls-tree master
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    test_main.c
> ls
test_main.c
----

Переименуем файл _test_main.c_ на _main.c_ средствами _git_.

[source, sh]
----
> git mv test_main.c main.c

> git commit -m "Rename test_main.c file"
[master c566f0e] Rename test_main.c file
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename test_main.c => main.c (100%)
----

Имя файла изменилось как в репозитории так и в рабочем каталоге.

[source, sh]
----
> git ls-tree master
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    main.c

> ls
main.c
----