= Простые SQL-запросы

== Запрос `INSERT INTO`

`INSERT INTO` - этот запрос используется для добавления двумя разными способами новых строк данных в таблицу в базе данных.

*Способ первый:*

[source,sql]
----
INSERT INTO months VALUES (1,'January',31);
----

Этот способ не подразумевает указания названий колонок, а лишь принимает значения в том порядке, в котором они указаны в таблице. Однако, если в будущем необходимо добавить дополнительные колонки, все предыдущие запросы работать не будут.

Для решения данной проблемы следует использовать *второй способ*. Его суть заключается в том, что перед вводом данных указываются названия колонок.

[source,sql]
----
INSERT INTO months (id,name,days) VALUES (2,'February',29);
----

== Запрос `SELECT`

`SELECT` - используется для выбора данных из базы данных. Возвращаемые данные сохраняются в таблице результатов, называемой результирующим набором.

[source,sql]
----
SELECT * FROM characters
----

Результатом данного запроса будет таблица со всеми данными в таблице `characters`. Знак звёздочки (`*`) означает то, что необходимо показать все столбцы из таблицы без исключений. Так как в базе данных обычно больше одной таблицы, нам необходимо указывать название таблицы, данные из которой требуется посмотреть. Сделать это можно используя ключевое слово `FROM`.

Когда необходимы лишь некоторые столбцы из таблицы, то можно указать их имена через запятую вместо звёздочки.

[source,sql]
----
SELECT name, weapon FROM characters
----

== Запрос `SELECT DISTINCT`

Оператор `SELECT DISTINCT` используется для возврата только отдельных (разных) значений. Внутри таблицы столбец часто содержит много повторяющихся значений и вам нужно только перечислить отличающиеся значения.

*Синтаксис:*

[source,sql]
----
SELECT DISTINCT column1, column2, ...
FROM table_name;
----

*Пример*, следующий оператор SQL выбирает только значения `DISTINCT` из столбца «name» в таблице `users`:

[source,sql]
----
SELECT DISTINCT name FROM users;
----

В следующем SQL-заявлении указано количество разных имен пользователей:

[source,sql]
----
SELECT COUNT(DISTINCT name) FROM users;
----

== Запрос `WHERE`

`WHERE` - это запрос позволяющий включить в вывод лишь некоторые конкретные строки. Данное ключевое слово позволяет фильтровать данные по определённому условию.

*Синтаксис:*

[source,sql]
----
SELECT column1, column2, ...
FROM table_name
WHERE condition;
----

*Пример предложения*, следующий оператор SQL выбирает всех пользователей с именем `name` в таблице `users`:

[source,sql]
----
SELECT * FROM users
WHERE name ='Том';
----

Следует отметить, что *SQL* требует одинарных кавычек вокруг текстовых значений (большинство систем баз данных также допускают двойные кавычки). Однако числовые поля не должны быть заключены в кавычки.

=== Операторы в разделе `WHERE`

Следующие операторы могут использоваться в предложении `WHERE`:

|===
|*Заголовок*|*Группа*
| `=` |Равно
|`!=` или `<>`|Не равно
| `>`|Больше чем
|`<`|	Меньше чем
|`>=`|	Больше или равно
|`\<=`|Меньше или равно
|`BETWEEN`|Между включенным диапазоном
|`LIKE`|Поиск по шаблону
|`IN`|Поиск данных по нескольким значениям, перечисленным через запятую
|===

== Операторы `AND`, `OR` и `NOT`

Предложение `WHERE` может быть объединено с операторами `AND`, `OR` и `NOT`. Операторы `AND` и `OR` используются для фильтрации записей на основе более чем одного условия:

* Оператор `AND` отображает запись, если все условия, разделенные символом `AND`, имеют значение `TRUE`.
* Оператор `OR` отображает запись, если любое из условий, разделенных `OR`, является `TRUE`.
* Оператор `NOT` отображает запись, если условие (и) *НЕ ИСТИНА*.

=== Оператор `AND`

*Синтаксис:*

[source,sql]
----
SELECT column1, column2, ...
FROM table_name
WHERE condition1 AND condition2 AND condition3 ...;
----

*Пример:*

Следующий оператор SQL выбирает все поля из `users`, где пол `gender` равен `1` (_женский_), а баланс `balance` больше или равен (`>=`) `1000`.

[source,sql]
----
SELECT * FROM users
WHERE gender = 1 AND balance >= 1000;
----

=== Оператор `OR`

*Синтаксис:*

[source,sql]
----
SELECT column1, column2, ...
FROM table_name
WHERE condition1 OR condition2 OR condition3 ...;
----

*Пример:*

Следующий оператор SQL выбирает все поля из `users`, где баланс пользователя `balance` равен `1000` или возраст пользователя `age` равен `25`.

[source,sql]
----
SELECT * FROM users
WHERE balance = 1000 OR age = 25;
----

=== Оператор `NOT`

*Синтаксис:*

[source,sql]
----
SELECT column1, column2, ...
FROM table_name
WHERE NOT condition;
----

*Пример:*

Следующий оператор SQL выбирает все поля из `users`, где возраст `age` не равен `30`:

[source,sql]
----
SELECT * FROM users
WHERE NOT age = 30
----

=== Объединение `AND`, `OR` и `NOT`

Также можно комбинировать операторы `AND`, `OR` и `NOT`.

Следующий оператор выбирает все поля из `users`, где возраст `age` равно `30`. И баланс `balance` больше `1000` или имя `name` равно `Том`.

*Пример:*

[source,sql]
----
SELECT * FROM users
WHERE age = 30 AND (balance > 1000 OR name = 'Том');
----

== Ключевое слово `ORDER BY`

Ключевое слово `ORDER BY` используется для сортировки результирующего набора в порядке возрастания или убывания. По умолчанию оно сортирует записи по возрастанию. Чтобы отсортировать записи в порядке убывания, используйте ключевое слово `DESC`. Для сортировки по возрастанию, используйте ключевое слово `ASC`.

*Синтаксис:*

[source,sql]
----
SELECT column1, column2, ...
FROM table_name
ORDER BY column1, column2, ... ASC|DESC;
----

*Пример:*

Следующий оператор выбирает всех пользователей из таблицы `users`, отсортированные по столбцу `name`:

[source,sql]
----
SELECT * FROM users
ORDER BY name;
----

== Значение `NULL`

Поле со значением `NULL` является полем без значения. Если поле в таблице является необязательным, можно вставить новую запись или обновить запись без добавления значения в это поле. Затем поле будет сохранено со значением `NULL`. Значение `NULL` отличается от нулевого значения или поля, содержащего пробелы.

=== Как проверить значения `NULL`?

Невозможно проверить значения `NULL` с операторами сравнения, такими как `=`, `<` или `<>`. Вместо этого нужно использовать операторы `IS NULL` и `NOT NULL`.

Синтаксис `IS NULL`:

[source,sql]
----
SELECT column_names
FROM table_name
WHERE column_name IS NULL;
----

Пример `IS NULL`:

Следующий оператор использует оператор `IS NULL` для перечисления всех пользователей, у которых нет телефона.

[source,sql]
----
SELECT name, fullname, phone FROM users
WHERE phone IS NULL;
----

Синтаксис `NOT NULL`:

[source,sql]
----
SELECT column_names
FROM table_name
WHERE column_name IS NOT NULL;
----

Пример `IS NOT NULL`: следующий оператор использует оператор `IS NOT NULL` для перечисления всех пользователей, у которых есть телефон.

[source,sql]
----
SELECT name, fullname, phone FROM users
WHERE phone IS NOT NULL;
----

== Запрос `UPDATE`

Зачастую необходимо изменить данные в таблице. В *SQL* это делается с помощью `UPDATE`.

Использование `UPDATE` включает в себя выбор таблицы, в которой находится поле подлежащее изменению. Запись нового значения осуществляется с помощью запроса `WHERE`, чтобы обозначить конкретное место в таблице.

*Синтаксис:*

[source,sql]
----
UPDATE table_name
SET column1 = value1, column2 = value2, ...
WHERE condition
----

*Пример:*

Предположим есть таблица с самыми высоко оценёнными сериалами всех времён. Однако в ней есть несоответствие: *Игра Престолов*  обозначена как комедия, изменим значение поля следующим запросом:

[source,sql]
----
UPDATE tv_series
SET genre = 'drama'
WHERE name = 'Game of Thrones';
----

== Удаление записей из таблицы c помощью `DELETE`.

Удаление записи из таблицы очень простая операция, всё что нужно - это обозначить, что необходимо удалить.

[source,sql]
----
DELETE FROM tv_series
WHERE id = 4;
----

NOTE: Необходимо убедиться что используется запрос `WHERE`, когда происходит удаление записи из таблицы. Иначе удалятся все записи.

=== Удалить все записи

Можно удалить все строки таблицы без удаления таблицы. Это означает, что структура таблицы, атрибуты и индексы будут неповрежденными:

[source,sql]
----
DELETE FROM table_name;
----

или:

[source,sql]
----
DELETE * FROM table_name;
----

== Предложение `SELECT TOP`

Предложение `SELECT TOP` используется для указания количества возвращаемых записей. Оно полезно для больших таблиц с тысячами записей. Возвращение большого количества записей может повлиять на производительность.

[source,sql]
----
SELECT column_name(s)
FROM table_name
WHERE condition
LIMIT number;
----

=== Примеры `TOP`, `LIMIT` и `ROWNUM`

Следующий оператор выбирает первые три записи из таблицы `users`:

[source,sql]
----
SELECT TOP 3 * FROM users;
----

Следующий оператор показывает эквивалентный пример, используя предложение `LIMIT`:

[source,sql]
----
SELECT * FROM users
LIMIT 3;
----

Следующий оператор показывает эквивалентный пример с использованием `ROWNUM`:

[source,sql]
----
SELECT * FROM users
WHERE ROWNUM <= 3;
----

=== Пример `TOP PERCENT`

Следующий оператор выбирает *первые 25% записей* из таблицы `users`:

[source,sql]
----
SELECT TOP 25 PERCENT * FROM users;
----

Следующий оператор выбирает первые 5 записи из таблицы `users`, где баланс `balance` равен `1000`:

[source,sql]
----
SELECT TOP 5 * FROM users
WHERE balance = 1000;
----

=== Пример `LIMIT`

Следующий оператор показывает эквивалентный пример, используя предложение `LIMIT`:

[source,sql]
----
SELECT * FROM users
WHERE balance = 1000
LIMIT 5;
----

Следующий оператор показывает эквивалентный пример с использованием `ROWNUM`:

[source,sql]
----
SELECT * FROM users
WHERE balance = 1000 AND ROWNUM <= 5;
----

== Оператор `LIKE`

Оператор `LIKE` используется в предложении `WHERE` для поиска заданного шаблона в столбце.

В сочетании с оператором `LIKE` используются два подстановочных знака:

* `%` - Знак процента представляет нулевой, один или несколько символов
* `_` - Подчеркнутый символ представляет собой один символ

[source,sql]
----
SELECT column1, column2, ...
FROM table_name
WHERE columnN LIKE pattern;
----

|===
|Выражение|	Описание
|`WHERE name LIKE 'text%'`|Находит любые значения, начинающиеся с `text`
|`WHERE name LIKE '%text'`|Находит любые значения, заканчивающиеся на `text`
|`WHERE name LIKE '%text%'`|Находит любые значения, которые имеют `text` в любой позиции
|`WHERE name LIKE '_text%'`|Находит любые значения, которые имеют `text` во второй позиции
|`WHERE name LIKE 'text_%_%'`|Находит любые значения, начинающиеся с `text` и длиной не менее 3 символов
|`WHERE name LIKE 'text%data'`|Находит любые значения, начинающиеся с `text` и заканчивающиеся на `data`
|===

=== Подстановочные знаки

Символ подстановки используется для замены любого другого символа в строке. Подстановочные символы используются с оператором `LIKE`. Оператор `LIKE` используется в предложении `WHERE` для поиска заданного шаблона в столбце.

==== Использование подстановочного знака

Следующий оператор SQL выбирает всех пользователей с `name`, начиная с любого символа, за которым следует `о`:

[source,sql]
----
SELECT * FROM users
WHERE name LIKE '_о';
----

Следующий оператор выбирает всех пользователей с `name` начиная с `Т`, за которыми, следует любой символ. А за ним следует `м`, за которым следует любой символ, а затем `с`:

[source,sql]
----
SELECT * FROM users
WHERE name LIKE 'Т_м_с';
----

==== Использование подстановочного знака `[charlist]`

Следующий оператор SQL выбирает всех пользователей с name, начиная с `Т`, `Р` или `Е`:

[source,sql]
----
SELECT * FROM users
WHERE name LIKE '[ТРЕ]%';
----

Следующий оператор SQL выбирает всех пользователей с `name`, начиная с `Т`, `Р` или `Е`:

[source,sql]
----
SELECT * FROM users
WHERE name LIKE '[Т-E]%'
----

==== Использование подстановочного знака `[!charlist]`

Два следующих оператора SQL выбирают всех пользователей с помощью `name NOT`, начинающегося с `Т`, `Р` или `E`:

[source,sql]
----
SELECT * FROM users
WHERE name LIKE '[!ТРЕ]%';
----

Или:

[source,sql]
----
SELECT * FROM users
WHERE name NOT LIKE '[ТРЕ]%';
----

== Оператор `IN`

Оператор `IN` позволяет указать несколько значений в предложении `WHERE`. Он является сокращением для нескольких условий `OR`.

*Синтаксис `IN`*

[source,sql]
----
SELECT column_name(s)
FROM table_name
WHERE column_name IN (value1, value2, ...);
----

*или:*

[source,sql]
----
SELECT column_name(s)
FROM table_name
WHERE column_name IN (SELECT STATEMENT);
----

*Например* выберем всех пользователей, которые находятся в странах `Испания`, `Франция` и `Бразилия`:

[source,sql]
----
SELECT * FROM users
WHERE country IN ('Испания', 'Франция', 'Бразилия');
----

Выберем всех пользователей, которые *НЕ расположены* в `Испания`, `Франция` и `Бразилия`:

[source,sql]
----
SELECT * FROM users
WHERE country NOT IN ('Испания', 'Франция', 'Бразилия');
----

== Оператор `BETWEEN` и `NOT BETWEEN`

Оператор `BETWEEN` выбирает значения в заданном диапазоне. Значения могут быть числами, текстом или датами.

*Синтаксис:*

[source,sql]
----
SELECT column_name(s)
FROM table_name
WHERE column_name BETWEEN value1 AND value2;
----

*Например* выберем все продукты с ценой `BETWEEN` `5` и `200`.

[source,sql]
----
SELECT * FROM product
WHERE price BETWEEN 5 AND 200;
----

Чтобы отобразить товары вне диапазона предыдущего примера, используйте `NOT BETWEEN`:

[source,sql]
----
SELECT * FROM product
WHERE price NOT BETWEEN 5 AND 200;
----

=== Пример `BETWEEN` с `IN`

Следующий оператор выбирает все товары с ценой `BETWEEN` `5` и `200` и не показывать товары с категориями `1`, `2`, `3`, `4`, `5`.

[source,sql]
----
SELECT * FROM product
WHERE (price BETWEEN 5 AND 200)
AND NOT category_id IN (1, 2, 3, 4, 5);
----

=== `BETWEEN` текстовых значений

Следующий оператор выбирает все товары с name `BETWEEN` `'Красный телефон'` и `'Серебристая клавиатура'`:

[source,sql]
----
SELECT * FROM product
WHERE name BETWEEN 'Красный телефон' AND 'Серебристая клавиатура'
ORDER BY name;
----

=== `NOT BETWEEN` текстовых значений

Следующий оператор выбирает все продукты с name `NOT BETWEEN` `'Красный телефон'` и `'Серебристая клавиатура'`:

[source,sql]
----
SELECT * FROM product
WHERE name NOT BETWEEN 'Красный телефон' AND 'Серебристая клавиатура'
ORDER BY name;
----

=== Пример `BETWEEN` с датами

Следующий оператор SQL выбирает все счета с помощью `date BETWEEN`.

[source,sql]
----
SELECT * FROM invoice
WHERE date BETWEEN #21.10.2017# AND #22.10.2017#;
----

== Псевдонимы `Aliases`

*SQL-псевдонимы* используются для предоставления таблицы или столбца таблицы временного имени. Псевдонимы часто используются, чтобы сделать имена столбцов более читабельными. Псевдоним существует только для продолжительности запроса.

Псевдонимы могут быть полезны, когда:

* В запросе содержится более одной таблицы
* Функции используются в запросе
* Названия столбцов большие или не очень читаемые
* Два или более столбца объединяются вместе

*Синтаксис:*

[source,sql]
----
SELECT column_name AS alias_name
FROM table_name;
----

*Синтаксис таблицы псевдонимов:*

[source,sql]
----
SELECT column_name(s)
FROM table_name AS alias_name;
----

=== Псевдоним для столбцов

Следующий оператор создает два псевдонима: один для столбца `user_id` и один для столбца `name`:

*Пример:*

[source,sql]
----
SELECT user_id as ID, name AS user
FROM users;
----

Следующий оператор создает два псевдонима: один для столбца `name` и один для столбца `address`:

[source,sql]
----
SELECT name AS user, address AS [Address User]
FROM users;
----

=== Псевдонимы для таблиц

Следующий оператор выбирает все счета от пользователя с помощью `user_id` и `name`. В запросе используются таблицы `users` и `invoice`, которым даются псевдонимы таблиц `u` и `o`:

[source,sql]
----
SELECT i.invoice_id, i.date, i.name
FROM users AS u, invoice AS i
WHERE u.name = "Том" AND u.user_id = i.user_id;
----
