= Проектирование баз данных

== Нормализация и денормализация баз данных

*Нормализация базы данных* - это процесс эффективной организации данных в базе данных. Есть две причины процесса нормализации:

* Устранение избыточных данных, например, хранение тех же данных в более чем одной таблице.
* Обеспечение зависимостей данных.

*Денормализация* — намеренное приведение структуры базы данных в состояние, не соответствующее критериям нормализации, обычно проводимое с целью ускорения операций чтения из базы за счет добавления избыточных данных.

*Нормализация* состоит из ряда принципов, которые помогают в создании хорошей структуры базы данных. Эти принципы делятся на нормальные формы, их цель в организации структуры базы данных таким образом, чтобы правильно организовать структуру базы данных.

=== Первая нормальная форма

Правила первой нормальной формы:

* В таблице не должно быть дублирующих строк.
* В каждой ячейке таблицы хранится атомарное значение (одно не составное значение).
* В столбце хранятся данные одного типа.
* Нет упорядочивания строк сверху вниз (другими словами, порядок строк не несет в себе никакой информации).
* Нет упорядочивания столбцов слева направо (другими словами, порядок столбцов не несет в себе никакой информации).

Пример, допустим есть ненормализованная таблица:

|===
|ID покупателя|ФИО|Заказ|Телефон
|10|Егоров Егор|Ноутбук Asus G53| Мобильный телефон 44 888 77 77, Домашний Телефон 8-77-77
|10|Егоров Егор|Телефон Nokia 5310| Мобильный телефон 44 888 77 77, Домашний Телефон 8-77-77
|10|Егоров Егор|Наушники LG 700|Мобильный телефон 44 888 77 77, Домашний Телефон 8-77-77
|===

Такая таблица нарушает требования первой нормальной формы. Ее следует разбить на две части, а затем соединить их с помощью ключа.

.Информация о клиенте
|===
|ID покупателя|ФИО|Мобильный телефон|Домашний телефон
|10|Егоров Егор|44 888 77 77|8-77-77
|===

.Информация о заказах
|===
|ID заказа |ID клиента |Заказ
|1|10|Ноутбук Asus G53
|2|10|Телефон Nokia 5310
|3|10|Наушники LG 700
|===

Такие таблицы соответствуют требованиям первой нормальной формы.

==== Вторая нормальная форма

*Правило второй нормальной формы* звучит следующим образом: отношение соответствует второй нормальной форме, если оно соответствует первой нормальной форме и каждый не ключевой атрибут неприводимо зависит от первичного ключа.

|===
|ФИО|Должность|Подразделение
|Егоров Егор|Программист|Отдел разработки ПО
|Иванов Иван|Бухгалтер|Бухгалтерия
|Борисов Борис|Продавец|Отдел реализации
|===

Допустим в организации каждому сотруднику присваивается уникальный табельный номер, который никогда не будет изменен. Таким образом, чтобы привести эту таблицу ко второй нормальной форме, необходимо добавить в нее еще один атрибут, т.е. столбец с табельным номером, который будет выступать первичным ключом.

|===
|Табельный номер|ФИО|Должность|Подразделение
|660|Егоров Егор|Программист|Отдел разработки ПО
|212|Иванов Иван|Бухгалтер|Бухгалтерия
|1024|Борисов Борис|Продавец|Отдел реализации
|===

==== Третья нормальная форма

*Правило третьей нормальной формы* звучит следующим образом: отношение находится в третьей нормальной форме, когда находится во второй нормальной форме и каждый не ключевой атрибут не транзитивно зависит от первичного ключа.

Иначе говоря, третья нормальная форма требует выносить все не ключевые поля, содержимое которых может относиться к нескольким записям таблицы в отдельные таблицы.

|===
|CourseID|Course|TeacherID|Teacher
|1|Математика|1|Егоров Егор
|2|Java|2|Иванов Иван
|3|Алгоритмы|2|Иванов Иван
|===

Такую ненормализованную таблицу требуется разбить на две разные таблицы:

|===
|TeacherID|Teacher
|1|Егоров Егор
|2|Иванов Иван
|===

Таким образом в первой таблице TeacherID является ключом, явный указывающий на преподавателя.

|===
|CourseID|Course|TeacherID
|1|Математика|1
|2|Java|2
|3|Алгоритмы|2
|===

==== Нормальная форма Бойса-Кодда

*Требование нормальной формы Бойса-Кодда* звучит следующим образом: таблица должна находиться в третьей нормальной форме и ключевые атрибуты составного ключа не должны зависеть от неключевых атрибутов. Отсюда следует, что требования нормальной формы Бойса-Кодда предъявляются только к таблицам, у которых первичный ключ составной.

*Пример*

Представим, что у нас есть организация, которая реализует множество различных проектов. При этом в каждом проекте работа ведётся по нескольким функциональным направлениям, в каждом из которых есть свой куратор. Сотрудник может быть куратором только того направления, на котором он специализируется, т.е. если сотрудник программист, он не может курировать в проекте направление, связанное с бухгалтерией.

Допустим, что нам нужно хранить информацию о кураторах всех проектов по каждому направлению в таблице, где *первичный ключ составной* «Проект + Направление:

|===
|Проект|Направление|Куратор
|1|Разработка|Егоров Егор
|1|Бухгалтерия|Иванов Иван
|2|Разработка|Егоров Егор
|3|Реализация|Андреев Андрей
|===

В данном случае таблица не находится в нормальной форме Бойса-Кодда, дело в том, что зная куратора, можно четко определить, какое направление он курирует, иными словами, часть составного ключа, т.е. «Направление», зависит от неключевого атрибута, т.е. «Куратора». Чтобы привести данную таблицу к нормальной форме Бойса-Кодда, необходимо сделать декомпозицию данного отношения, т.е. разбить эту таблицу на несколько таблиц.

.Таблица кураторов
|===
|Идентификатор куратора|ФИО|Направление
|1|Егоров Егор|Разработка
|2|Иванов Иван|Бухгалтерия
|3|Андреев Андрей|Реализация
|===

.Таблица связи кураторов и проектов
|===
|Проект |Идентификатор куратора
|1|1
|1|2
|2|1
|3|3
|===
