= Простые SQL-запросы

== Создание таблицы

Для того чтобы создать таблицу в *SQL*, используется выражение `CREATE TABLE`. Он принимает в качестве параметров все колонки, которые необходимо внести, а также их типы данных. Пример создания таблицы с названием `Months`, в которой будет три колонки:

* `id` - порядковый номер месяца (целочисленный тип или `int`).
* `name` - название месяца.
* `days` - число дней в конкретном месяце.

Код создания будет выглядеть следующим образом:

[source,sql]
----
CREATE TABLE months (id int, name varchar(10), days int);
----

== `INSERT INTO`

`INSERT INTO` - этот запрос используется для добавления двумя разными способами новых строк данных в таблицу в базе данных.

*Способ первый:*

[source,sql]
----
INSERT INTO months VALUES (1,'January',31);
----

Этот способ не подразумевает указания названий колонок, а лишь принимает значения в том порядке, в котором они указаны в таблице. Однако, если в будущем необходимо добавить дополнительные колонки, все предыдущие запросы работать не будут.

Для решения данной проблемы следует использовать *второй способ*. Его суть заключается в том, что перед вводом данных указываются названия колонок.

[source,sql]
----
INSERT INTO months (id,name,days) VALUES (2,'February',29);
----

== `SELECT`

`SELECT` - это запрос используемый в случае, если необходимо показать данные в таблице.

[source,sql]
----
SELECT * FROM characters
----

Результатом данного запроса будет таблица со всеми данными в таблице characters. Знак звёздочки (`*`) означает то, что необходимо показать все столбцы из таблицы без исключений. Так как в базе данных обычно больше одной таблицы, нам необходимо указывать название таблицы, данные из которой требуется посмотреть. Сделать это можно используя ключевое слово FROM. Когда необходимы лишь некоторые столбцы из таблицы, то можно указать их имена через запятую вместо звёздочки.

[source,sql]
----
SELECT name, weapon FROM characters
----

== `WHERE`

`WHERE` - это запрос позволяющий включить в вывод лишь некоторые конкретные строки. Данное ключевое слово позволяет фильтровать данные по определённому условию.

Например:

[source,sql]
----
SELECT *
FROM characters
WHERE weapon = 'pistol';
----

В следующем запросе выведутся те персонажи, которые в качестве оружия используют пистолет.

== Операторы `AND` & `OR`

Операторы `AND` & `OR` условия в `WHERE` могут быть написаны с использованием логических операторов (`AND`/`OR`) и математические операторы сравнения (`=`, `<`, `>`, `\<=`, `>=`, `<>`).

К примеру есть табличка, в которой записаны данные о четырех самых продаваемых музыкальных альбомах всех времён. Выведем только те, жанром которых является рок, а продажи были меньше, чем 50 миллионов копий.

[source,sql]
----
SELECT *
FROM albums
WHERE genre = 'rock' AND sales_in_millions <= 50
ORDER BY released
----

== `IN/BETWEEN/LIKE`

Условия в `WHERE` могут быть записаны с использованием ещё нескольких команд, которыми являются:

* `IN` — сравнивает значение в столбце с несколькими возможными значениями и возвращает `true`, если значение совпадает хотя бы с одним значением
* `BETWEEN` — проверяет, находится ли значение в каком-то промежутке.
* `LIKE` — ищет по шаблону.

К примеру, можно сделать запрос для вывода данных об альбомах в жанре `pop` или `soul`:

[source,sql]
----
SELECT * FROM albums WHERE genre IN ('pop','soul');
----

Если необходимо вывести все альбомы, которые были выпущены в промежутке между `1975` и `1985` годом, можно использовать следующую запись:

[source,sql]
----
SELECT * FROM albums WHERE released BETWEEN 1975 AND 1985;
----

Также, если необходимо вывести все альбомы, в названии которых есть буква `R`, можно использовать следующую запись:

[source,sql]
----
SELECT * FROM albums WHERE album LIKE '%R%';
----

Знак `%` означает любую последовательность символов (0 символов тоже считается за последовательность). Если необходимо вывести все альбомы, первая буква в названии которых — `R`, то запись слегка изменится:

[source,sql]
----
SELECT * FROM albums WHERE album LIKE 'R%';
----

В *SQL* также есть инверсия. Для этого достаточно написать `NOT` перед любым логическим выражением в условии (`NOT BETWEEN` и так далее).

== `UPDATE`

Зачастую необходимо изменить данные в таблице. В *SQL* это делается с помощью `UPDATE`.

Использование `UPDATE` включает в себя выбор таблицы, в которой находится поле подлежащее изменению. Запись нового значения осуществляется с помощью запроса `WHERE`, чтобы обозначить конкретное место в таблице.

Предположим есть таблица с самыми высоко оценёнными сериалами всех времён. Однако в ней есть несоответствие: `Игра Престолов` обозначена как комедия, изменим значение поля следующим запросом:

[source,sql]
----
UPDATE tv_series
SET genre = 'drama'
WHERE name = 'Game of Thrones';
----

== Удаление записей из таблицы

Удаление записи из таблицы через *SQL* - очень простая операция. Всё, что нужно - это обозначить, что необходимо удалить.

[source,sql]
----
DELETE FROM tv_series
WHERE id = 4;
----

Примечание: необходимо убедиться что используется запрос `WHERE`, когда происходит удаление записи из таблицы. Иначе удалятся все записи.

== Удаление таблиц

Если необходимо все данные из таблицы, но при этом оставить саму таблицу, следует использовать команду `TRUNCATE`:

[source,sql]
----
TRUNCATE TABLE table_name;
----

В случае, если необходимо удалить саму таблицу, то следует использовать команду `DROP`:

[source,sql]
----
DROP TABLE table_name;
----
